import { hashCorpus, hashDocumentBytes, isCorpusDocument } from './corpus';

describe('isCorpusDocument', () => {
  it('includes spec index files, child specs, verify notes and findings', () => {
    expect(isCorpusDocument('docs/specs/_root/0011-eval-suite/index.md')).toBe(true);
    expect(isCorpusDocument('docs/specs/_root/0012-agent/0012-public-evals-page.md')).toBe(true);
    expect(isCorpusDocument('docs/specs/_root/0012-agent/verify.md')).toBe(true);
    expect(isCorpusDocument('docs/specs/_root/0012-agent/findings/2026-08-31-x.md')).toBe(true);
    expect(isCorpusDocument('docs/specs/_root/0003-frontend.md')).toBe(true);
  });

  it('excludes every rationale.md, which is the load bearing exclusion', () => {
    // These record options that were REJECTED. Retrieved, they read exactly
    // like current decisions, which is a new way to be confidently wrong.
    expect(isCorpusDocument('docs/specs/_root/0012-agent/rationale.md')).toBe(false);
    expect(isCorpusDocument('docs/specs/_root/0008-rejected/rationale.md')).toBe(false);
  });

  it('includes eval writeups but not the README or the results data', () => {
    expect(isCorpusDocument('docs/evals/interview/0012-phase-two-public-evals-page.md')).toBe(true);
    expect(isCorpusDocument('docs/evals/interview/README.md')).toBe(false);
    // Regenerated by every eval run. In the corpus it would change the hash on
    // every run, so AC-12's staleness refusal would fire for a file nobody
    // wrote, and a check that cries wolf gets bypassed.
    expect(isCorpusDocument('docs/evals/interview/scoreboard.md')).toBe(false);
    expect(isCorpusDocument('docs/evals/interview/results/2026-08-30-abc.json')).toBe(false);
    expect(isCorpusDocument('docs/evals/interview/results/notes.md')).toBe(false);
  });

  it('excludes anything that is not markdown, and anything outside the corpus roots', () => {
    expect(isCorpusDocument('docs/evals/interview/published.json')).toBe(false);
    expect(isCorpusDocument('docs/specs/_root/0012-agent/diagram.png')).toBe(false);
    expect(isCorpusDocument('docs/reviews/2026-08-31-review.md')).toBe(false);
    expect(isCorpusDocument('README.md')).toBe(false);
    expect(isCorpusDocument('apps/api/src/main.ts')).toBe(false);
  });
});

describe('hashDocumentBytes', () => {
  it('hashes raw bytes, so the hash does not move when the chunker changes', () => {
    const a = hashDocumentBytes(Buffer.from('# Spec\n\nbody\n'));
    expect(a).toBe(hashDocumentBytes(Buffer.from('# Spec\n\nbody\n')));
    expect(a).not.toBe(hashDocumentBytes(Buffer.from('# Spec\n\nbody changed\n')));
  });
});

describe('hashCorpus', () => {
  const docs = [
    { path: 'docs/specs/_root/0002/index.md', hash: 'bbb' },
    { path: 'docs/specs/_root/0001/index.md', hash: 'aaa' },
  ];

  it('does not depend on the order documents were collected in', () => {
    expect(hashCorpus(docs)).toBe(hashCorpus([...docs].reverse()));
  });

  it('changes when any document changes', () => {
    const changed = [{ ...docs[0], hash: 'ccc' }, docs[1]];
    expect(hashCorpus(changed)).not.toBe(hashCorpus(docs));
  });

  it('changes when a document is added or removed', () => {
    const added = [...docs, { path: 'docs/specs/_root/0003/index.md', hash: 'ddd' }];
    expect(hashCorpus(added)).not.toBe(hashCorpus(docs));
    expect(hashCorpus([docs[0]])).not.toBe(hashCorpus(docs));
  });

  it('changes when a document is renamed but its content is identical', () => {
    // A rename changes what the persona would cite, so it must change the hash.
    const renamed = [{ path: 'docs/specs/_root/0001/renamed.md', hash: 'aaa' }, docs[0]];
    expect(hashCorpus(renamed)).not.toBe(hashCorpus(docs));
  });
});
