import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import * as path from 'node:path';
import { hashDataset } from '../eval/dataset-hash';

/**
 * Which committed documents the retrieval corpus contains, and how its
 * contents are hashed (spec 0012 phase three, AC-1 and AC-11).
 *
 * The selection is deliberately mechanical rather than described in prose,
 * because "every spec and child spec" is ambiguous and a corpus that drifts
 * from what the manifest claims defeats the whole reproducibility argument.
 *
 * `rationale.md` is excluded on purpose and this is the load bearing
 * exclusion: those files record options that were weighed and REJECTED. A
 * retrieved passage from one reads exactly like a current decision when it is
 * the opposite, which would be a new way for the persona to be confidently
 * wrong.
 */

/** A document that belongs in the corpus, with its content already read. */
export type CorpusDocument = {
  /** Repo relative, POSIX separators, so the hash is stable across platforms. */
  path: string;
  text: string;
  /** sha256 of the raw file bytes. */
  hash: string;
};

/** What `corpus.json` holds. */
export type CorpusManifest = {
  corpusHash: string;
  chunkCount: number;
  embeddedAt: string;
  documents: { path: string; hash: string }[];
};

const INCLUDED_DIRECTORIES = ['docs/specs', 'docs/evals/interview'] as const;

/**
 * Decides whether one repo relative path belongs in the corpus.
 *
 * Kept as a predicate over an already walked path rather than a glob library:
 * the rules are few, they are easier to test this way, and every exclusion
 * here has a reason worth reading.
 */
export function isCorpusDocument(repoRelativePath: string): boolean {
  const segments = repoRelativePath.split('/');
  const file = segments[segments.length - 1];
  if (!file.endsWith('.md')) return false;

  // Rejected options must never be retrievable as decisions.
  if (file === 'rationale.md') return false;

  if (repoRelativePath.startsWith('docs/evals/interview/')) {
    // Only writeups. README.md explains how to run the suite, which is
    // instructions rather than a record of thinking, and results/ is data.
    if (segments.length !== 4) return false;
    // scoreboard.md is REGENERATED by every eval run. Including it would make
    // the corpus hash change on every run, so the staleness refusal in AC-12
    // would fire constantly for a file nobody wrote, and a check that cries
    // wolf is a check people learn to bypass.
    return file !== 'README.md' && file !== 'scoreboard.md';
  }

  if (!repoRelativePath.startsWith('docs/specs/')) return false;

  // A spec's own findings are records of what was measured, so they belong.
  if (segments.includes('findings')) return true;

  // index.md is the umbrella or single spec; verify.md is a decision record
  // of how the thing is checked; NNNN-*.md are child specs.
  if (file === 'index.md' || file === 'verify.md') return true;
  return /^\d{4}-.+\.md$/.test(file);
}

/** sha256 over the raw bytes, deliberately not over chunked output. */
export function hashDocumentBytes(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * The hash the eval records beside `datasetHash`, over the whole document set.
 *
 * Reuses `hashDataset`, the same helper the golden case set uses, rather than
 * a second hash pipeline: two inputs to one comparability decision should not
 * be computed two different ways.
 */
export function hashCorpus(documents: { path: string; hash: string }[]): string {
  const sorted = [...documents].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return hashDataset(sorted.map(({ path: p, hash }) => ({ path: p, hash })));
}

/**
 * Walks the corpus directories and reads every document that belongs.
 *
 * An unreadable file is a hard failure rather than a silent omission: a
 * corpus quietly missing a document would hash differently from the one the
 * manifest describes, and the refusal in AC-12 would then fire for a reason
 * nobody could explain.
 */
export function collectCorpus(repoRoot: string): CorpusDocument[] {
  const documents: CorpusDocument[] = [];

  const walk = (absoluteDir: string): void => {
    let entries: string[];
    try {
      entries = readdirSync(absoluteDir);
    } catch {
      return; // a directory that does not exist yet is not an error
    }
    for (const entry of entries.sort()) {
      const absolute = path.join(absoluteDir, entry);
      const relative = path.relative(repoRoot, absolute).split(path.sep).join('/');
      if (statSync(absolute).isDirectory()) {
        walk(absolute);
        continue;
      }
      if (!isCorpusDocument(relative)) continue;
      let bytes: Buffer;
      try {
        bytes = readFileSync(absolute);
      } catch (cause) {
        throw new Error(
          `corpus: cannot read ${relative}, which the selection rules include. ` +
            'A document that belongs in the corpus but cannot be read is a hard failure, ' +
            'never a silent omission.',
          { cause },
        );
      }
      documents.push({ path: relative, text: bytes.toString('utf8'), hash: hashDocumentBytes(bytes) });
    }
  };

  for (const dir of INCLUDED_DIRECTORIES) walk(path.join(repoRoot, dir));
  return documents.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
